package javax.naming;
import java.util.Hashtable;
public interface Context {
    String INITIAL_CONTEXT_FACTORY="java.naming.factory.initial";
    String URL_PKG_PREFIXES="java.naming.factory.url.pkgs";
    String PROVIDER_URL="java.naming.provider.url";
    String BATCHSIZE="java.naming.batchsize";
    String REFERRAL="java.naming.referral";
    String SECURITY_AUTHENTICATION="java.naming.security.authentication";
    String SECURITY_PRINCIPAL="java.naming.security.principal";
    String SECURITY_CREDENTIALS="java.naming.security.credentials";
    Object lookup(String n) throws NamingException;
    void bind(String n,Object o) throws NamingException;
    void rebind(String n,Object o) throws NamingException;
    void unbind(String n) throws NamingException;
    void rename(String a,String b) throws NamingException;
    NamingEnumeration<NameClassPair> list(String n) throws NamingException;
    NamingEnumeration<Binding> listBindings(String n) throws NamingException;
    void destroySubcontext(String n) throws NamingException;
    Context createSubcontext(String n) throws NamingException;
    Object lookupLink(String n) throws NamingException;
    NameParser getNameParser(String n) throws NamingException;
    String composeName(String n,String p) throws NamingException;
    Object addToEnvironment(String k,Object v) throws NamingException;
    Object removeFromEnvironment(String k) throws NamingException;
    Hashtable<?,?> getEnvironment() throws NamingException;
    void close() throws NamingException;
    String getNameInNamespace() throws NamingException;
    Object lookup(Name n) throws NamingException;
    void bind(Name n,Object o) throws NamingException;
    void rebind(Name n,Object o) throws NamingException;
    void unbind(Name n) throws NamingException;
    void rename(Name a,Name b) throws NamingException;
    NamingEnumeration<NameClassPair> list(Name n) throws NamingException;
    NamingEnumeration<Binding> listBindings(Name n) throws NamingException;
    void destroySubcontext(Name n) throws NamingException;
    Context createSubcontext(Name n) throws NamingException;
    Object lookupLink(Name n) throws NamingException;
    NameParser getNameParser(Name n) throws NamingException;
    Name composeName(Name a,Name b) throws NamingException;
}
