name: Unzip bitcoinj source

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Unzip and move bitcoinj
        run: |
          cd wallet/src/wallet/java
          unzip bitcoinj-master.zip
          mv bitcoinj-master/core/src/main/java/org bitcoinj-master/core/src/main/java/org/bitcoinj ./org/
          rm -rf bitcoinj-master.zip bitcoinj-master
          
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add bitcoinj source
          file_pattern: wallet/src/wallet/java/org/