name: Unzip jcip-annotations

on:
  workflow_dispatch:   # chạy tay từ tab Actions

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip java.zip
        run: |
          cd wallet/src/wallet
          # nếu file java.zip nằm đúng chỗ này
          unzip -o java.zip -d java
          rm java.zip

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzip java.zip" || echo "No changes"
          git push