name: Unzip bitcoinj

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip file
        run: |
          cd wallet/src/wallet
          unzip -o bitcoinj-0.17.1.zip -d bitcoinj-0.17.1
          rm bitcoinj-0.17.1.zip

      - name: Commit kết quả
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzip bitcoinj-0.17.1.zip" || echo "No changes"
          git push
