name: Unzip proto

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip proto.zip
        run: |
          cd wallet/src/wallet
          unzip -o proto.zip -d proto
          rm proto.zip

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzip proto.zip" || echo "No changes"
          git push